name: Android Build CI

on:
    pull_request:
        branches: [ develop, main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            
            - name: BASE_URL
              run: |
                echo BASE_URL=$BASE_URL > local.properties
              shell: bash
              env:
                 API_KEY: ${{ secrets.BASE_URL }}


            - name: Ktlint Check
              run: ./gradlew --no-daemon ktlintCheck --continue
            
            - name: Create file
              run: cat /home/runner/work/Don-t-Forget---Android/Don-t-Forget---Android/app/google-services.json | base64
            
            - name: Putting data
              env:
                DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
              run: echo $DATA > /home/runner/work/Don-t-Forget---Android/Don-t-Forget---Android/app/google-services.json

            - name: Build with Gradle
              run: ./gradlew build
