name: ktlint

on:
    pull_request:
        branches:
            - main
            - develop
jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
             - name: Ktlint Check
               run: ./gradlew --no-daemon ktlintCheck --continue

             - name: Build with Gradle
               run: ./gradlew build
               with:
                  github_token: ${{ secrets.nexters_token }}
                  reporter: github-pr-check # Change reporter
