name: ktlint

on:
    pull_request:
        branches:
            - main
            - develop
jobs:
    ktlint:
        runs-on: ubuntu-latest

        steps:
            - name: ktlint
              run: ./gradlew --no-daemon ktlintCheck --continue
              with:
                  github_token: ${{ secrets.nexters_token }}
                  reporter: github-pr-check # Change reporter
            - name: Build with Gradle
              run: ./gradlew build
